<?xml version="1.0" encoding="utf-8"?>
<xsl:transform
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:html="http://www.w3.org/1999/xhtml"
    version="1.0"
>

    <xsl:output
        method="text"
    />

    <xsl:template match="/">
        <xsl:text># Auto-generated file. Do not edit!&#xA;</xsl:text>
        <xsl:text># Generated by FlickrMakefile.xslt&#xA;</xsl:text>
        <xsl:text>&#xA;</xsl:text>
        <xsl:text>FLICKR_IMAGES+=\&#xA;</xsl:text>
        <xsl:for-each select="//flickrImage">
            <xsl:text>    </xsl:text><xsl:value-of select="@basename" /><xsl:text> \&#xA;</xsl:text>
        </xsl:for-each>
        <xsl:text>&#xA;</xsl:text>

        <xsl:text>SCALED_IMAGES:=$(addprefix gfx/flickr/,$(addsuffix .jpg,$(FLICKR_IMAGES)))&#xA;</xsl:text>
        <xsl:text>&#xA;</xsl:text>

        <xsl:text>.PHONY: all&#xA;</xsl:text>
        <xsl:text>all: scaleImages&#xA;</xsl:text>
        <xsl:text>&#xA;</xsl:text>

        <xsl:text>.PHONY: scaleImages&#xA;</xsl:text>
        <xsl:text>scaleImages: $(SCALED_IMAGES)&#xA;</xsl:text>
        <xsl:text>&#xA;</xsl:text>

        <xsl:text>.PHONY: deleteScaledImages&#xA;</xsl:text>
        <xsl:text>clean: deleteScaledImages&#xA;</xsl:text>
        <xsl:text>deleteScaledImages:&#xA;</xsl:text>
        <xsl:text>&#x9;rm -f $(SCALED_IMAGES)&#xA;</xsl:text>
        <xsl:text>&#xA;</xsl:text>

        <xsl:text>gfx/flickr/%.jpg: gfx/flickr/%_o.jpg&#xA;</xsl:text>
        <xsl:text>&#x9;&lt;$^ anytopnm | pnmscale -xysize 400 300 | pnmtojpeg &gt;$@&#xA;</xsl:text>
        <xsl:text>&#xA;</xsl:text>

        <xsl:for-each select="//flickrImage">
            <xsl:text>gfx/flickr/</xsl:text><xsl:value-of select="@basename" /><xsl:text>_o.jpg:&#xA;</xsl:text>
            <xsl:text>&#x9;wget -O $@ </xsl:text><xsl:value-of select="@imageUrl" /><xsl:text>&#xA;</xsl:text>
            <xsl:text>&#xA;</xsl:text>
        </xsl:for-each>
    </xsl:template>

</xsl:transform>
